[package]
name = "arc_installer"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }
reqwest = {version = "0.12", features = ["blocking"]}
sha2 = "0.9"
